Import-Module WebAdministration

$user = Read-Host "Enter the user name of the local user"
$pwd = Read-Host "Enter password (sorry, no masking)"

$wildcard = "MIIFLTCCBBWgAwIBAgIIa6UjGuZ7YAcwDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTUwMjE5MTkzNzM5WhcNMTgwMjE5MTU0NzM4WjA/MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0ZWQxGjAYBgNVBAMMESouY3Jpc3BoZWFsdGgub3JnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtvZswZX7xkVTraiS1V13axS5vl7hLQoEIH2udCPK7i7uCd94fi7ddQCBXY6fPu9Alt22+iOBlKbbc74CcRp+U6oNssARoLJIJXWDalBh40ImFU2dRZTpgJgnGN0+fk9z4sLXydg8F1IiS5NJMUXXimWVmjDSbQH/h22w/aLnm5Vx/aq3pDUuSgU3RZn7HE5oLuMR/DdP5n8sPozB5vz4px0sFkjo94Vxl7iVtAnnvcVAHDjaXsj1Pk0GlcOVoeBd14W89AwRuvUV1UicqJ1fjEQ+/fuxdW0GIvgbs3ITPALyGS5ZWbqNYpfJDJOg5SUdJ1AupaphtX3aAMTxPg4LkwIDAQABo4IBtTCCAbEwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDgYDVR0PAQH/BAQDAgWgMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2RpZzJzMS04Ny5jcmwwUwYDVR0gBEwwSjBIBgtghkgBhv1tAQcXATA5MDcGCCsGAQUFBwIBFitodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMHYGCCsGAQUFBwEBBGowaDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRkeS5jb20vMEAGCCsGAQUFBzAChjRodHRwOi8vY2VydGlmaWNhdGVzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvZ2RpZzIuY3J0MB8GA1UdIwQYMBaAFEDCvSeOzDSDMKIz1/tss/C0LIDOMC0GA1UdEQQmMCSCESouY3Jpc3BoZWFsdGgub3Jngg9jcmlzcGhlYWx0aC5vcmcwHQYDVR0OBBYEFBgSnB7bUmbgzigmI9undDtmice3MA0GCSqGSIb3DQEBCwUAA4IBAQAnUvZzSNB4H1v53mhkUekAoDVA/LRU9VK11nB8HvwEugaIXURtyoWfzDUftreXF/N8Yoc32IbFlQNCeJBUDCuhd6QaxsQNYT8DhTQIu+KWAc70Cfu56dOfp9VB7he35fDQi4Z4L9lzD5CdaTCBEYOONjrkAXzDidpTKvLyw+VHaqtkfKJpyl6IBOjiprM6ZGubQYQXyJNMiXpf5w7hl5QEswWZAngH3zeUspb/Mwv66yCgfDEJf9EPz0s54Vrtmtp4DCH6UEPZFQktoP/vBxX+UzqCl+eZjpBXuv+u2hwNY6qhNn7r8KGtpnJU0XBdoVjnwfXunL/2KV/+c2+08dWz"

Write-Host $env:COMPUTERNAME\$user

Set-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -location 'Default Web Site' -filter "system.webServer/security/authentication/iisClientCertificateMappingAuthentication" -name "oneToOneCertificateMappingsEnabled" -value "True"

Remove-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -location 'Default Web Site' -filter "system.webServer/security/authentication/iisClientCertificateMappingAuthentication/oneToOneMappings" -name "." -AtElement @{userName="$env:COMPUTERNAME\$user";password="$pwd";certificate="$wildcard"}
Add-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST' -location 'Default Web Site' -filter "system.webServer/security/authentication/iisClientCertificateMappingAuthentication/oneToOneMappings" -name "." -value @{userName="$env:COMPUTERNAME\$user";password="$pwd";certificate="$wildcard"}

Write-Host "Please review the output above for any errors"
Read-Host "press enter to continue..."